[package]
name = "renderer"
version = "0.1.0"
edition = "2021"

[features]
default = ["desktop"]
desktop = ["dep:winit"]

[dependencies]
wgpu = { workspace = true }
winit = { workspace = true, optional = true }
glam = { workspace = true }
bytemuck = { workspace = true }
image = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
pollster = { workspace = true }
serde_yaml = { workspace = true }
