[package.metadata.deb]
name = "pixi-ai"
maintainer = "granizm"
copyright = "2024, granizm"
license-file = ["LICENSE", "4"]
depends = "$auto"
section = "utility"
priority = "optional"
assets = [
    ["../../target/release/pixi-ai", "usr/bin/pixi-ai", "755"],
]
